#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

dotfiles=(
  ackrc
  gemrc
  gitconfig
  gitignore_global
  gitattributes_global
  irbrc
  selected_editor
  tm_properties
  vim
  vimrc
  zshrc
  railsrc
)

for dotfile in ${dotfiles[@]}
do
  linkname=${HOME}/.${dotfile}
  if [ -e "$linkname" ]; then
    if [ -L "$linkname" ]; then
      echo "$linkname is a link, updating..."
    else
      echo "$linkname exists, backing up..."
      mv $linkname $linkname.bak
      echo "Creating $linkname"
    fi
  else
    echo "Creating $linkname"
  fi
  ln -sfn ${DIR}/${dotfile} $linkname
done

